# Generated by Django 4.0.6 on 2022-07-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
